environment:
  matrix:
  - TARGET: stable-x86_64-pc-windows-msvc
  - TARGET: stable-i686-pc-windows-msvc
  - TARGET: stable-x86_64-pc-windows-gnu
  - TARGET: stable-i686-pc-windows-gnu
  - TARGET: beta-x86_64-pc-windows-msvc
  - TARGET: beta-i686-pc-windows-msvc
  - TARGET: beta-x86_64-pc-windows-gnu
  - TARGET: beta-i686-pc-windows-gnu
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
  - TARGET: nightly-i686-pc-windows-gnu

matrix:
  allow_failures:
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
  - TARGET: nightly-i686-pc-windows-gnu

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
  - cargo build

test_script:
  - copy nul examples\common\consumer_key
  - copy nul examples\common\consumer_secret
  - cargo test
