environment:
  matrix:
    - TARGET: stable-x86_64-pc-windows-msvc
    - TARGET: stable-i686-pc-windows-msvc
    - TARGET: stable-x86_64-pc-windows-gnu
    - TARGET: stable-i686-pc-windows-gnu
    - TARGET: beta-x86_64-pc-windows-msvc
    - TARGET: beta-i686-pc-windows-msvc
    - TARGET: beta-x86_64-pc-windows-gnu
    - TARGET: beta-i686-pc-windows-gnu
    - TARGET: nightly-x86_64-pc-windows-msvc
    - TARGET: nightly-i686-pc-windows-msvc
    - TARGET: nightly-x86_64-pc-windows-gnu
    - TARGET: nightly-i686-pc-windows-gnu
    allow_failures:
      - TARGET: nightly-x86_64-pc-windows-msvc
      - TARGET: nightly-i686-pc-windows-msvc
      - TARGET: nightly-x86_64-pc-windows-gnu
      - TARGET: nightly-i686-pc-windows-gnu

install:
  - ps: if (ls -r . -fi "*.rs" | sls "`t") { throw "Found tab character" }
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV

build_script:
  - cargo build

test_script:
  - copy nul examples\common\consumer_key
  - copy nul examples\common\consumer_secret
  - cargo test
