[package]
name = "egg-mode"
version = "0.6.0"
authors = ["QuietMisdreavus <bryan@icesoldier.me>"]
description = "Library to interact with the Twitter API"
documentation = "https://shiva.icesoldier.me/doc/egg_mode/"
homepage = "https://github.com/QuietMisdreavus/twitter-rs"
repository = "https://github.com/QuietMisdreavus/twitter-rs"
keywords = ["twitter"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
hyper = "0.9.10"
url = "1.1.1"
rand = "0.3.14"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.19"
mime = "0.2.1"
chrono = "0.2.25"
regex = "0.1.77"
lazy_static = "0.2.1"
unicode-normalization = "0.1.2"

[dev-dependencies]
yaml-rust = "0.3.4"
