[package]
name = "egg-mode"
version = "0.12.0"
authors = ["QuietMisdreavus <grey@quietmisdreavus.net>"]
description = "Library to interact with the Twitter API"
documentation = "https://tonberry.quietmisdreavus.net/doc/egg_mode/"
repository = "https://github.com/QuietMisdreavus/twitter-rs"
keywords = ["twitter"]
categories = ["api-bindings"]
license = "MPL-2.0"
readme = "README.md"

[badges]
travis-ci = { repository = "QuietMisdreavus/twitter-rs" }
appveyor = { repository = "QuietMisdreavus/twitter-rs" }

[dependencies]
hyper = "0.12.29"
hyper-tls = "0.3.2"
hyper-rustls = { version = "0.16.1", optional = true }
native-tls = { version = "0.2.3", optional = true }
futures = "0.1.27"
tokio = "0.1.21"
url = "1.7.2"
rand = "0.6.5"
hmac = "0.7.0"
sha-1 = "0.8.1"
mime = "0.3.13"
chrono = { version = "0.4.6", features = ["serde"] }
regex = "1.1.6"
lazy_static = "1.3.0"
serde = "1.0.92"
serde_json = "1.0.39"
serde_derive = "1.0.92"
base64 = "0.10.1"

[features]
default = ["native-tls"]
