[package]
name = "egg-mode"
version = "0.11.0"
authors = ["QuietMisdreavus <grey@quietmisdreavus.net>"]
description = "Library to interact with the Twitter API"
documentation = "https://tonberry.quietmisdreavus.net/doc/egg_mode/"
repository = "https://github.com/QuietMisdreavus/twitter-rs"
keywords = ["twitter"]
categories = ["api-bindings"]
license = "MPL-2.0"
readme = "README.md"

[badges]
travis-ci = { repository = "QuietMisdreavus/twitter-rs" }
appveyor = { repository = "QuietMisdreavus/twitter-rs" }

[dependencies]
hyper = "0.11.2"
hyper-tls = "0.1.2"
native-tls = "0.1.4"
futures = "0.1.14"
tokio-core = "0.1.6"
url = "1.5.1"
rand = "0.3.16"
hmac = "0.4.2"
sha-1 = "0.4.1"
rustc-serialize = "0.3.24"
mime = "0.3.0"
chrono = "0.4.0"
regex = "0.1.80"
lazy_static = "0.2.8"
