[package]
name = "egg-mode"
version = "0.8.0"
authors = ["QuietMisdreavus <grey@quietmisdreavus.net>"]
description = "Library to interact with the Twitter API"
documentation = "https://shiva.icesoldier.me/doc/egg_mode/"
repository = "https://github.com/QuietMisdreavus/twitter-rs"
keywords = ["twitter"]
categories = ["api-bindings"]
license = "Apache-2.0"
readme = "README.md"

[badges]
travis-ci = { repository = "QuietMisdreavus/twitter-rs" }
appveyor = { repository = "QuietMisdreavus/twitter-rs" }

[dependencies]
hyper = "0.10.0"
hyper-native-tls = "0.2.1"
native-tls = "0.1.1"
url = "1.1.1"
rand = "0.3.14"
ring = "0.9.4"
rustc-serialize = "0.3.19"
mime = "0.2.1"
chrono = "0.2.25"
regex = "0.1.77"
lazy_static = "0.2.1"
unicode-normalization = "0.1.2"

[dev-dependencies]
yaml-rust = "0.3.4"
