[package]
name = "egg-mode"
version = "0.13.0"
authors = ["QuietMisdreavus <grey@quietmisdreavus.net>", "Alex Whitney <adwhit@fastmail.com>"]
description = "Library to interact with the Twitter API"
documentation = "https://tonberry.quietmisdreavus.net/doc/egg_mode/"
repository = "https://github.com/QuietMisdreavus/twitter-rs"
keywords = ["twitter"]
categories = ["api-bindings"]
license = "MPL-2.0"
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "QuietMisdreavus/twitter-rs" }
appveyor = { repository = "QuietMisdreavus/twitter-rs" }

[dependencies]
base64 = "0.10.1"
chrono = { version = "0.4.6", features = ["serde"] }
futures = "0.1.27"
hmac = "0.7.0"
hyper = "0.12.29"
hyper-rustls = { version = "0.16.1", optional = true }
hyper-tls = "0.3.2"
lazy_static = "1.3.0"
native-tls = { version = "0.2.3", optional = true }
mime = "0.3.13"
rand = "0.6.5"
regex = "1.1.6"
serde = "1.0.92"
serde_json = "1.0.39"
serde_derive = "1.0.92"
sha-1 = "0.8.1"
tokio = "0.1.21"
url = "1.7.2"

[features]
default = ["native-tls"]

[dev-dependencies]
yansi = "0.5.0"
